
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: redis
  annotations:
    k8s.kuboard.cn/workload: redis
    k8s.kuboard.cn/displayName: redis
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: redis
spec:
  selector:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: zydnme
      nodePort: 0
  sessionAffinity: None

---
metadata:
  name: mysql-conf
  namespace: default
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2021-07-13T09:58:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:MYSQL_DATABASE': {}
          'f:MYSQL_PASSWORD': {}
          'f:MYSQL_ROOT_PASSWORD': {}
          'f:MYSQL_USER': {}
          'f:my.cnf': {}
data:
  MYSQL_DATABASE: nacos_devtest
  MYSQL_PASSWORD: nacos
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: nacos
  my.cnf: |-
    [mysqld]

    init_connect='SET collation_connection = utf8_unicode_ci'
    init_connect='SET NAMES utf8'
    character-set-server=utf8
    collation-server=utf8_unicode_ci
    skip-character-set-client-handshake
kind: ConfigMap
apiVersion: v1

---
metadata:
  name: naocos-env
  namespace: default
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2021-07-13T09:58:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:JVM_MS': {}
          'f:JVM_XMN': {}
          'f:JVM_XMS': {}
          'f:JVM_XMX': {}
          'f:MODE': {}
          'f:MYSQL_SERVICE_DB_NAME': {}
          'f:MYSQL_SERVICE_HOST': {}
          'f:MYSQL_SERVICE_PASSWORD': {}
          'f:MYSQL_SERVICE_PORT': {}
          'f:MYSQL_SERVICE_USER': {}
          'f:PREFER_HOST_MODE': {}
          'f:SPRING_DATASOURCE_PLATFORM': {}
data:
  JVM_MS: 512m
  JVM_XMN: 1024m
  JVM_XMS: 1024m
  JVM_XMX: 1024m
  MODE: standalone
  MYSQL_SERVICE_DB_NAME: nacos_devtest
  MYSQL_SERVICE_HOST: mysql
  MYSQL_SERVICE_PASSWORD: nacos
  MYSQL_SERVICE_PORT: '3306'
  MYSQL_SERVICE_USER: nacos
  PREFER_HOST_MODE: hostname
  SPRING_DATASOURCE_PLATFORM: mysql
kind: ConfigMap
apiVersion: v1

---
metadata:
  name: rabbitmq-conf
  namespace: default
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2021-07-13T09:58:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:RABBITMQ_PASSWORD': {}
          'f:RABBITMQ_USERNAME': {}
          'f:RABBITMQ_VHOST': {}
data:
  RABBITMQ_PASSWORD: admin
  RABBITMQ_USERNAME: admin
  RABBITMQ_VHOST: /zebra-dev
kind: ConfigMap
apiVersion: v1

---
metadata:
  name: redis-conf
  namespace: default
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2021-07-13T09:58:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:redis.conf': {}
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    loglevel notice
    databases 16
    always-show-logo yes
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    replica-serve-stale-data yes
    replica-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-disable-tcp-nodelay no
    replica-priority 100
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    replica-lazy-flush no
    appendonly no
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    lua-time-limit 5000
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 0
    notify-keyspace-events ""
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes
    aof-rewrite-incremental-fsync yes
    rdb-save-incremental-fsync yes
kind: ConfigMap
apiVersion: v1

